# RVDB Canonical ID Overrides
#
# These mappings define permanent RVDB IDs.
#
# Format:
#
# current_id: canonical_id
#

developer.nintendo.rnd1: developer.nintendo.rnd1

genre.rpg: genre.rpg

platform.nintendo.snes: platform.nintendo.snes

game.zelda_link_to_the_past: game.zelda.link.to.the.past

nintendo_nes: platform.nintendo.nes
